# Generated by Django 3.0.6 on 2020-05-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0002_auto_20200522_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarking',
            name='str_bench_ciclo',
            field=models.CharField(blank=True, db_column='Ci', max_length=256, null=True),
        ),
    ]
