# Generated by Django 3.0.6 on 2020-05-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0003_areageografica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_emp', models.AutoField(db_column='id_Empresa', primary_key=True, serialize=False)),
                ('str_emp_nombre', models.CharField(db_column='Nombre', max_length=256)),
                ('str_emp_descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=256, null=True)),
                ('id_emp_centro_principal', models.ForeignKey(blank=True, db_column='id_CentroPrincipal', on_delete=django.db.models.deletion.CASCADE, to='ModelsMaster.AreaGeografica')),
                ('id_emp_sector', models.ForeignKey(db_column='id_Sector', on_delete=django.db.models.deletion.CASCADE, to='ModelsMaster.Sector')),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
    ]
