# Generated by Django 3.0.6 on 2020-05-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0004_auto_20200522_2133'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='benchmarking',
            table='benchmarkings',
        ),
    ]
