# Generated by Django 3.0.6 on 2020-05-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0008_auto_20200525_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='id_ob_parent',
            field=models.ForeignKey(blank=True, db_column='id_ObjetivoPadre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Objetivo'),
        ),
        migrations.AlterField(
            model_name='areageografica',
            name='id_ag_nag',
            field=models.ForeignKey(db_column='id_NivelArea', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.NivelAreaGeografica'),
        ),
        migrations.AlterField(
            model_name='areageografica',
            name='id_ag_parent',
            field=models.ForeignKey(blank=True, db_column='id_AreaSuperior', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.AreaGeografica'),
        ),
        migrations.AlterField(
            model_name='benchmarking',
            name='id_bench_ag',
            field=models.ForeignKey(db_column='id_AreaGeografica', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.AreaGeografica'),
        ),
        migrations.AlterField(
            model_name='benchmarking',
            name='id_bench_sc',
            field=models.ForeignKey(db_column='id_Sector', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Sector'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id_emp_ag',
            field=models.ForeignKey(blank=True, db_column='id_CentroPrincipal', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.AreaGeografica'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id_emp_sc',
            field=models.ForeignKey(db_column='id_Sector', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Sector'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='id_md_emp',
            field=models.ForeignKey(db_column='id_Empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Empresa'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='id_ob_pc',
            field=models.ForeignKey(db_column='id_Capitulo', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.PuntosCapitulo'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='id_ob_to',
            field=models.ForeignKey(db_column='id_Tipo_Objetivo', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.TipoObjetivo'),
        ),
        migrations.AlterField(
            model_name='puntoscapitulo',
            name='id_pc_am',
            field=models.ForeignKey(db_column='id_Ambito', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Ambito'),
        ),
        migrations.AlterField(
            model_name='puntoscapitulo',
            name='id_pc_md',
            field=models.ForeignKey(db_column='id_Modelo', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Modelo'),
        ),
        migrations.AlterModelTable(
            name='puntoscapitulo',
            table='puntos_capitulo',
        ),
        migrations.DeleteModel(
            name='ObjetivoRelacionado',
        ),
    ]
