# Generated by Django 3.0.6 on 2020-05-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0009_auto_20200526_1207'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='puntoscapitulo',
            table='puntos_capitulos',
        ),
    ]
