# Generated by Django 3.0.6 on 2020-05-27 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0011_auto_20200526_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambito',
            name='bool_am_eliminado',
        ),
        migrations.RemoveField(
            model_name='ambito',
            name='id_am',
        ),
        migrations.RemoveField(
            model_name='ambito',
            name='str_am_descripcion',
        ),
        migrations.RemoveField(
            model_name='ambito',
            name='str_am_nombre',
        ),
        migrations.AddField(
            model_name='ambito',
            name='Descripcion',
            field=models.CharField(blank=True, db_column='AM_Descripcion', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ambito',
            name='Eliminado',
            field=models.BooleanField(db_column='AM_Eliminado', default=False),
        ),
        migrations.AddField(
            model_name='ambito',
            name='Id',
            field=models.AutoField(db_column='AM_Id_Ambito', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ambito',
            name='Nombre',
            field=models.CharField(db_column='AM_Nombre', max_length=256),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='id_ob_parent',
            field=models.ForeignKey(db_column='Id_Objetivo_Padre', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Objetivo'),
        ),
        migrations.AlterModelTable(
            name='puntoscapitulo',
            table='puntos_capitulo',
        ),
        migrations.AlterModelTable(
            name='tipointerviniente',
            table='tipo_intervinientes',
        ),
        migrations.AlterModelTable(
            name='tipoobjetivo',
            table='tipo_objetivos',
        ),
    ]
