# Generated by Django 3.0.6 on 2020-05-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0002_auto_20200521_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaGeografica',
            fields=[
                ('id_ag', models.AutoField(db_column='id_AreaGeografica', primary_key=True, serialize=False)),
                ('str_ag_nombre', models.CharField(db_column='Nombre', max_length=256)),
                ('str_ag_descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=256, null=True)),
                ('bool_ag_eliminado', models.BooleanField(db_column='eliminado', default=False)),
                ('id_ag_nag', models.ForeignKey(db_column='id_NivelArea', on_delete=django.db.models.deletion.CASCADE, to='ModelsMaster.NivelAreaGeografica')),
                ('id_ag_parent', models.ForeignKey(blank=True, db_column='id_AreaSuperior', null=True, on_delete=django.db.models.deletion.CASCADE, to='ModelsMaster.AreaGeografica')),
            ],
            options={
                'db_table': 'areas_geograficas',
            },
        ),
    ]
