# Generated by Django 3.0.6 on 2020-05-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0005_auto_20200522_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='id_emp_sector',
            new_name='id_emp_sc',
        ),
        migrations.AddField(
            model_name='empresa',
            name='bool_emp_eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
