# Generated by Django 3.0.6 on 2020-05-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0006_auto_20200522_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areageografica',
            name='id_ag_nag',
            field=models.ForeignKey(db_column='id_NivelArea', on_delete=django.db.models.deletion.PROTECT, to='ModelsMaster.NivelAreaGeografica'),
        ),
        migrations.AlterField(
            model_name='areageografica',
            name='id_ag_parent',
            field=models.ForeignKey(blank=True, db_column='id_AreaSuperior', null=True, on_delete=django.db.models.deletion.PROTECT, to='ModelsMaster.AreaGeografica'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='bool_emp_eliminado',
            field=models.BooleanField(db_column='eliminado', default=False),
        ),
        migrations.CreateModel(
            name='Benchmarking',
            fields=[
                ('id_bench', models.AutoField(db_column='id_Bench', primary_key=True, serialize=False)),
                ('str_bench_nombre', models.CharField(blank=True, db_column='Nombre', max_length=256, null=True)),
                ('str_bench_descripcion', models.CharField(db_column='Descripcion', max_length=256)),
                ('int_bench_valor', models.IntegerField(db_column='Valor')),
                ('int_bench_año', models.IntegerField(db_column='Año')),
                ('str_bench_ciclo', models.CharField(db_column='Ciclo', max_length=256)),
                ('bool_bench_eliminado', models.BooleanField(db_column='eliminado', default=False)),
                ('id_bench_ag', models.ForeignKey(db_column='id_AreaGeografica', on_delete=django.db.models.deletion.PROTECT, to='ModelsMaster.AreaGeografica')),
                ('id_bench_sc', models.ForeignKey(blank=True, db_column='id_Sector', null=True, on_delete=django.db.models.deletion.PROTECT, to='ModelsMaster.Sector')),
            ],
        ),
    ]
