# Generated by Django 3.0.6 on 2020-05-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0007_auto_20200522_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarking',
            name='int_bench_año',
            field=models.IntegerField(blank=True, db_column='Año', null=True),
        ),
        migrations.AlterField(
            model_name='benchmarking',
            name='int_bench_valor',
            field=models.IntegerField(blank=True, db_column='Valor', null=True),
        ),
        migrations.AlterField(
            model_name='benchmarking',
            name='str_bench_ciclo',
            field=models.CharField(blank=True, db_column='Ciclo', max_length=256, null=True),
        ),
    ]
